import {getFeed} from '../sources/collector.js';
function json(data,status=200,extra={}){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, s-maxage=300, stale-while-revalidate=600','x-content-type-options':'nosniff',...extra}})}
function params(req){const u=new URL(req.url);return {u,search:u.searchParams}}
function matches(s,p){const q=(p.q||'').toLowerCase();if(q&&!`${s.title} ${s.hostname}`.toLowerCase().includes(q))return false;if(p.host&&s.hostType!==p.host)return false;if(p.framework&&s.framework!==p.framework)return false;if(p.minScore&&s.score<Number(p.minScore))return false;return true}
function sortSites(sites,sort){const a=[...sites];if(sort==='score')return a.sort((x,y)=>y.score-x.score);if(sort==='random')return a.sort(()=>Math.random()-.5);return a.sort((x,y)=>new Date(y.discoveredAt||y.checkedAt)-new Date(x.discoveredAt||x.checkedAt))}
export async function handleSites(req,runtimeEnv={}){const {search}=params(req);const data=await getFeed({runtimeEnv});const filtered=sortSites(data.sites.filter(s=>matches(s,{q:search.get('q')||'',host:search.get('host')||'',framework:search.get('framework')||'',minScore:search.get('minScore')||''})),search.get('sort')||'newest');const limit=Math.min(48,Math.max(1,Number(search.get('limit')||24)));const page=Math.max(1,Number(search.get('page')||1));const start=(page-1)*limit;const sites=filtered.slice(start,start+limit);return json({sites:sites.map(publicSite),nextPage:start+limit<filtered.length,totalHint:filtered.length,facets:{hosts:[...new Set(data.sites.map(s=>s.hostType))],frameworks:[...new Set(data.sites.map(s=>s.framework))]}},200)}
export async function handleSite(req,runtimeEnv={}){const {search}=params(req);const host=(search.get('host')||'').toLowerCase();if(!host)return json({error:'host is required'},400);const data=await getFeed({runtimeEnv});const site=data.sites.find(s=>s.hostname===host);if(!site)return json({error:'site not found'},404);return json(publicSite(site),200)}
export async function handleRandom(req,runtimeEnv={}){const data=await getFeed({runtimeEnv});if(!data.sites.length)return json({error:'no sites available'},404);return json(publicSite(data.sites[Math.floor(Math.random()*data.sites.length)]),200)}
export async function handleCron(req,runtimeEnv={}){const secret=runtimeEnv.CRON_SECRET ?? (typeof process!=='undefined'&&process.env?process.env.CRON_SECRET:'');const provided=req.headers.get('authorization')?.replace(/^Bearer\s+/i,'')||req.headers.get('x-cron-secret');if(secret&&provided!==secret)return json({error:'unauthorized'},401);const data=await getFeed({refresh:true,runtimeEnv});return json({ok:true,generatedAt:data.generatedAt,count:data.sites.length,sourceStats:data.sourceStats},200,{'cache-control':'no-store'})}
export async function handleHealth(){return json({ok:true,name:'SiteScout',time:new Date().toISOString()},200,{'cache-control':'no-store'})}
function publicSite(s){return {hostname:s.hostname,title:s.title,url:s.url,screenshot:s.screenshot||null,hostType:s.hostType,framework:s.framework||'Other',score:s.score,breakdown:s.breakdown,signals:{https:s.signals.https,status:s.signals.status,loadMs:s.signals.loadMs,title:s.signals.title,description:s.signals.description,ogImage:s.signals.ogImage,viewport:s.signals.viewport,securityHeaders:s.signals.securityHeaders>0},discoveredAt:s.discoveredAt,checkedAt:s.checkedAt,discoveredLabel:relativeTime(s.discoveredAt)}}
function relativeTime(iso){if(!iso)return 'Recently discovered';const d=Date.now()-new Date(iso).getTime();if(!Number.isFinite(d)||d<0)return 'Recently discovered';const m=Math.floor(d/60000);if(m<60)return `${m}m ago`;const h=Math.floor(m/60);if(h<24)return `${h}h ago`;return `${Math.floor(h/24)}d ago`}
